# app/config/routing.yml
app:
    resource: '@AppBundle/Controller/'
    type: annotation

Msg_list:
    path:    /msgboard/{id}
    defaults: { _controller: AppBundle:Msg:list, id: 1 }
    requirements:
        id: '\d+'

Msg_show:
    path:    /msgboard/{slug}
    defaults: { _controller: AppBundle:Msg:show }

